deb-preconf-drbl: add option "-s" to set etc file
deb-preconf-drbl: add option "-s" to set /etc/default/nis.
By default /etc/default/nis is not created since newer nis package
(version >= 4, from Debian 11 or Ubuntu 21.04) has included it.

diff --git a/scripts/sbin/deb-preconf-drbl b/scripts/sbin/deb-preconf-drbl
--- a/scripts/sbin/deb-preconf-drbl
+++ b/scripts/sbin/deb-preconf-drbl
@@ -15,7 +15,21 @@ DRBL_SCRIPT_PATH="${DRBL_SCRIPT_PATH:-/usr/share/drbl}"
 # Settings
 DEBCONF=/var/cache/debconf/config.dat
 DEFAULT_NIS=/etc/default/nis
+set_etc_nis="no"
 [ ! -f "$DEBCONF" ] && mkdir -p "$(dirname $DEBCONF)"
+
+ocs_file="$0"
+ocs=`basename $ocs_file`
+#
+while [ $# -gt 0 ]; do
+ case "$1" in
+   -s|--set-nis-etc) set_etc_nis="yes"; shift;;
+   -*)     echo "${0}: ${1}: invalid option" >&2
+           USAGE >& 2
+           exit 2 ;;
+   *)      break ;;
+ esac
+done
 
 # isc-dhcp-server
 debconf-set-selections <<EOF
@@ -36,8 +50,10 @@ debconf-set-selections <<EOF
 nis     nis/domain      string  localdomain
 EOF
 
-[ -f /etc/default/nis ] && rm -f /etc/default/nis
-cat << EOF >> $DEFAULT_NIS
+# About NIS etc settings
+[ -f /etc/default/nis ] && mv -f /etc/default/nis /etc/default/nis.drblsave
+if [ "$set_etc_nis" = "yes" ]; then
+  cat << EOF >> $DEFAULT_NIS
 #
 # /etc/defaults/nis	Configuration settings for the NIS daemons.
 #
@@ -74,5 +90,6 @@ YPPASSWDDARGS=
 # Additional options to be given to ypxfrd when it is started. 
 YPXFRDARGS=
 EOF
+fi
 
 echo "localdomain" > /etc/defaultdomain
