ready for supporting syslinux 6.

diff --git a/scripts/sbin/drbl-functions b/scripts/sbin/drbl-functions
--- a/scripts/sbin/drbl-functions
+++ b/scripts/sbin/drbl-functions
@@ -2348,9 +2348,9 @@ parse_cmdline_option() {
 } # parse_cmdline_option
 #
 output_netinstall_syslinux_pxelinux_menu() {
-  local TDIR="$1"  # Where netinstall kernel/initrd exists (/tftpboot/nbi_img)
-  local PXECFG_DIR_FNAME="$2"  # Where pxeliux cfg file exists (/tftpboot/nbi_img/pxelinux.cfg/)
-  local menu_hint ni_ver ni_arch
+  local TDIR  # Where netinstall kernel/initrd exists (/tftpboot/nbi_img)
+  local PXECFG_DIR_FNAME  # Where pxeliux cfg file exists (/tftpboot/nbi_img/pxelinux.cfg/)
+  local menu_hint ni_ver ni_arch boot_file_dir
   # output the netinstall menu
   # Here 2 types: Linux and BSD
   # The netinstall kernel files (linux) or pxeboot file (bsd) in /tftpboot/nbi_img are, e.g.:
@@ -2368,6 +2368,31 @@ output_netinstall_syslinux_pxelinux_menu() {
   # Type 2: for BSD, the file names are like:
   # OpenBSD-4.2-i386-pxeboot.0
   # FreeBSD-7.0-i386-pxeboot.0
+
+  while [ $# -gt 0 ]; do
+   case "$1" in
+     -p|--prefix)
+           shift
+           if [ -z "$(echo $1 |grep ^-.)" ]; then
+             # skip the -xx option, in case 
+             boot_file_dir="$1"
+             shift
+           fi
+           if [ -z "$boot_file_dir" ]; then
+             echo "-p is used, but no \"boot_file_dir\" assigned."
+             echo "$msg_program_stop"
+             [ "$save_restore_error_log" = "yes" ] && copy_error_log
+             exit 1
+           fi
+           ;;
+     -*)   echo "${0}: ${1}: invalid option" >&2
+           exit 2 ;;
+     *)    break ;;
+   esac
+  done
+
+  TDIR="$1" 
+  PXECFG_DIR_FNAME="$2"
   
   # Type 1: Linux
   for inet in $TDIR/vmlinuz-netinstall-*; do
@@ -2503,11 +2528,12 @@ label $img_menu
   MENU HIDE
   MENU LABEL $des
   # MENU PASSWD
-  kernel $kernel
-  append initrd=$img $ramdisk_size_opt $extra_append
+  kernel $boot_file_dir$kernel
+  append initrd=$boot_file_dir$img $ramdisk_size_opt $extra_append
   $menu_hint
   TEXT HELP
-  $des
+  * Boot menu for BIOS machine
+  * $des
   ENDTEXT
 
 PXE_END
@@ -2533,9 +2559,10 @@ label $img_menu
   MENU HIDE
   MENU LABEL $des
   # MENU PASSWD
-  kernel $img
+  kernel $boot_file_dir$img
   TEXT HELP
-  $des
+  * Boot menu for BIOS machine
+  * $des
   ENDTEXT
 
 PXE_END
@@ -2546,7 +2573,7 @@ get_syslinux_binary_for_dos_linux() {
   local sysl_dir="$1"
   # syslinux_ver is not required. If it's not assigned, the latest one on the web will be used.
   local syslinux_ver="$2"
-  local syslinux_tarball syslinux_ver_subdir syslinux_required_c32 syslinux_extra_c32
+  local syslinux_tarball syslinux_ver_subdir syslinux_extra_c32 dirprefix syslinux_efi_coms
   [ -z "$sysl_dir" -o ! -d "$sysl_dir" ] && echo "No sysl_dir!" && exit 1
   # syslinux_binsrc_url is like:
   # http://www.kernel.org/pub/linux/utils/boot/syslinux/
@@ -2562,36 +2589,80 @@ get_syslinux_binary_for_dos_linux() {
   syslinux_ver_subdir="$(LC_ALL=C echo "$syslinux_ver" | sed -r -e "s/\.[[:digit:]]*$/\.xx/g")"
   echo "Downloading $syslinux_binsrc_url/$syslinux_ver_subdir/$syslinux_tarball..."
   wget $wget_opt -P $sysl_dir $syslinux_binsrc_url/$syslinux_ver_subdir/$syslinux_tarball
-  # Those required c32 files (menu.c32, vesamenu.c32 and chain.c2). We force to copy this again to avoid the version on DRBL server does not match the downloaded on.
-  syslinux_required_c32="syslinux-${syslinux_ver}/com32/menu/menu.c32 syslinux-${syslinux_ver}/com32/menu/vesamenu.c32 syslinux-${syslinux_ver}/com32/chain/chain.c32"
+  # For syslinux 6.x, due to EFI feature was added, *.c32 might be in different dirs, e.g. for menu.c32:
+  # $ tar tvJf syslinux-5.10.tar.xz | grep -w menu.c32
+  # -rwxrwxr-x mfleming/syslinux  25808 2013-06-05 03:33 syslinux-5.10/com32/menu/menu.c32
+  # $ tar tvjf syslinux-6.01.tar.bz2 |grep -w menu.c32
+  # -rwxrwxr-x mfleming/syslinux  25708 2013-07-04 21:26 syslinux-6.01/bios/com32/menu/menu.c32
+  # -rwxrwxr-x mfleming/syslinux  26012 2013-07-04 21:27 syslinux-6.01/efi32/com32/menu/menu.c32
+  # -rwxrwxr-x mfleming/syslinux  31416 2013-07-04 21:28 syslinux-6.01/efi64/com32/menu/menu.c32
+  # Therefore we have to parse them...
+  if [ -n "$(tar -tvjf $sysl_dir/syslinux-${syslinux_ver}.tar.bz2 | \
+	     grep -w "bios/com32/menu/menu.c32")" ]; then
+    dirprefix="bios/"
+  else
+    dirprefix_bios=""
+  fi 
   # For syslinux 5.x, ./com32/elflink/ldlinux/ldlinux.c32, ./com32/lib/libcom32.c32, and ./com32/libutil/libutil.c32 are required.
   for i in $sys_pxelinux_v5p_required_c32; do
     if [ -n "$(LC_ALL=C tar -tvjf $sysl_dir/syslinux-${syslinux_ver}.tar.bz2 | grep -Ew $i)" ]; then
-      syslinux_extra_c32="syslinux-${syslinux_ver}/com32/elflink/ldlinux/ldlinux.c32 syslinux-${syslinux_ver}/com32/lib/libcom32.c32 syslinux-${syslinux_ver}/com32/libutil/libutil.c32" 
+      syslinux_extra_c32="syslinux-${syslinux_ver}/${dirprefix}com32/elflink/ldlinux/ldlinux.c32 syslinux-${syslinux_ver}/${dirprefix}com32/lib/libcom32.c32 syslinux-${syslinux_ver}/${dirprefix}com32/libutil/libutil.c32" 
       break
     fi
   done
-  # Extract win32/syslinux.exe and linux/syslinux
+  # Extract win32/syslinux.exe, linux/syslinux and more. This is for BIOS machine
   echo "Extracting files..."
+  mkdir -p $sysl_dir/bios/
   (
-   cd $sysl_dir
+   cd $sysl_dir/bios/
    # From syslinux 3.73, linux/syslinux is hardlink to linux/syslinux-nomtools, therefore we have to use --wildcards to extract it. Otherwise it will fail.
-   tar --wildcards -xvjf syslinux-${syslinux_ver}.tar.bz2 syslinux-${syslinux_ver}/com32/menu/menu.c32 syslinux-${syslinux_ver}/com32/menu/vesamenu.c32 syslinux-${syslinux_ver}/com32/chain/chain.c32 syslinux-${syslinux_ver}/win32/syslinux.exe syslinux-${syslinux_ver}/win64/syslinux64.exe syslinux-${syslinux_ver}/linux/syslinux* syslinux-${syslinux_ver}/extlinux/extlinux* syslinux-${syslinux_ver}/mbr/mbr.bin $syslinux_extra_c32
-   mv -f syslinux-${syslinux_ver}/com32/menu/menu.c32 .
-   mv -f syslinux-${syslinux_ver}/com32/menu/vesamenu.c32 .
-   mv -f syslinux-${syslinux_ver}/com32/chain/chain.c32 .
-   mv -f syslinux-${syslinux_ver}/win32/syslinux.exe . 
-   mv -f syslinux-${syslinux_ver}/win64/syslinux64.exe . 
-   mv -f syslinux-${syslinux_ver}/mbr/mbr.bin .
-   mv -f syslinux-${syslinux_ver}/linux/syslinux .
-   mv -f syslinux-${syslinux_ver}/extlinux/extlinux .
+   tar --wildcards -xvjf ../syslinux-${syslinux_ver}.tar.bz2 syslinux-${syslinux_ver}/${dirprefix}com32/menu/menu.c32 syslinux-${syslinux_ver}/${dirprefix}com32/menu/vesamenu.c32 syslinux-${syslinux_ver}/${dirprefix}com32/chain/chain.c32 syslinux-${syslinux_ver}/${dirprefix}win32/syslinux.exe syslinux-${syslinux_ver}/${dirprefix}win64/syslinux64.exe syslinux-${syslinux_ver}/${dirprefix}linux/syslinux* syslinux-${syslinux_ver}/${dirprefix}extlinux/extlinux* syslinux-${syslinux_ver}/${dirprefix}mbr/mbr.bin $syslinux_extra_c32
+   mv -f syslinux-${syslinux_ver}/${dirprefix}com32/menu/menu.c32 .
+   mv -f syslinux-${syslinux_ver}/${dirprefix}com32/menu/vesamenu.c32 .
+   mv -f syslinux-${syslinux_ver}/${dirprefix}com32/chain/chain.c32 .
+   mv -f syslinux-${syslinux_ver}/${dirprefix}win32/syslinux.exe . 
+   mv -f syslinux-${syslinux_ver}/${dirprefix}win64/syslinux64.exe . 
+   mv -f syslinux-${syslinux_ver}/${dirprefix}mbr/mbr.bin .
+   mv -f syslinux-${syslinux_ver}/${dirprefix}linux/syslinux .
+   mv -f syslinux-${syslinux_ver}/${dirprefix}extlinux/extlinux .
    if [ -n "$syslinux_extra_c32" ]; then
-      mv -f syslinux-${syslinux_ver}/com32/elflink/ldlinux/ldlinux.c32 .
-      mv -f syslinux-${syslinux_ver}/com32/lib/libcom32.c32 .
-      mv -f syslinux-${syslinux_ver}/com32/libutil/libutil.c32 .
-      chmod 644 $sys_pxelinux_v5p_required_c32
+      mv -f syslinux-${syslinux_ver}/${dirprefix}com32/elflink/ldlinux/ldlinux.c32 .
+      mv -f syslinux-${syslinux_ver}/${dirprefix}com32/lib/libcom32.c32 .
+      mv -f syslinux-${syslinux_ver}/${dirprefix}com32/libutil/libutil.c32 .
+      chmod 644 *.c32
    fi
   )
+  # For EFI machine
+  if [ "$live_efi_boot_loader" = "syslinux" ]; then
+    if [ -n "$dirprefix" ]; then
+      # This means the downloaded syslinux support EFI (for version >=6.01), then we should prepare that, too. Here we only add efi64, since efi32 is not very common for modern machine.
+      # Ref: http://www.rodsbooks.com/efi-bootloaders/syslinux.html especially the tarball http://www.rodsbooks.com/efi-bootloaders/syslinux-6.01.pre5-1.tgz
+      syslinux_efi_coms="menu.c32 vesamenu.c32 ldlinux.c32 chain.c32 libutil.c32 libcom32.c32"
+      # ./efi64/efi/syslinux.efi -> bootx64.efi
+      # ./efi64/com32/elflink/ldlinux/ldlinux.e64
+      mkdir -p $sysl_dir/efi/
+      (
+       cd $sysl_dir/efi/
+       tar --wildcards -xvjf ../syslinux-${syslinux_ver}.tar.bz2 \
+       syslinux-${syslinux_ver}/efi64/efi/syslinux.efi \
+       syslinux-${syslinux_ver}/efi64/com32/elflink/ldlinux/ldlinux.e64 \
+       syslinux-${syslinux_ver}/efi64/com32/menu/menu.c32 \
+       syslinux-${syslinux_ver}/efi64/com32/menu/vesamenu.c32 \
+       syslinux-${syslinux_ver}/efi64/com32/chain/chain.c32 \
+       syslinux-${syslinux_ver}/efi64/com32/lib/libcom32.c32 \
+       syslinux-${syslinux_ver}/efi64/com32/libutil/libutil.c32
+    
+       mv -f syslinux-${syslinux_ver}/efi64/efi/syslinux.efi bootx64.efi
+       mv -f syslinux-${syslinux_ver}/efi64/com32/elflink/ldlinux/ldlinux.e64 .
+       mv -f syslinux-${syslinux_ver}/efi64/com32/menu/menu.c32 .
+       mv -f syslinux-${syslinux_ver}/efi64/com32/menu/vesamenu.c32 .
+       mv -f syslinux-${syslinux_ver}/efi64/com32/chain/chain.c32 .
+       mv -f syslinux-${syslinux_ver}/efi64/com32/lib/libcom32.c32 .
+       mv -f syslinux-${syslinux_ver}/efi64/com32/libutil/libutil.c32 .
+       chmod 644 ldlinux.e64 *.c32
+      )
+    fi
+  fi
 } # end of get_syslinux_binary_for_dos_linux
 #
 put_syslinux_makeboot_for_usb_flash() {
@@ -2611,19 +2682,29 @@ put_syslinux_makeboot_for_usb_flash() {
   # Try to find the version of syslinux
   # Use strings to find the version, the output is like:
   # SYSLINUX 3.71 Debian-2008-08-04
-  SYSLINUX_VER="$(LC_ALL=C strings $sysl_dir/syslinux | grep -iE "^SYSLINUX.*[[:digit:]]+" | awk -F" " '{print $2}')"
+  SYSLINUX_VER="$(LC_ALL=C strings $sysl_dir/bios/syslinux | grep -iE "^SYSLINUX.*[[:digit:]]+" | awk -F" " '{print $2}')"
   echo "SYSLINUX version: $SYSLINUX_VER" > $t_dir/utils/win32/VERSION.txt
   echo "SYSLINUX version: $SYSLINUX_VER" > $t_dir/utils/linux/VERSION.txt
   echo "Precompiled binary syslinux files were extracted from $syslinux_binsrc_url/syslinux-${syslinux_ver}.tar.bz2" > $t_dir/utils/README.txt
-  cp -af $sysl_dir/{menu.c32,vesamenu.c32,chain.c32} $t_dir/syslinux/
-  cp -af $sysl_dir/{syslinux.exe,syslinux64.exe} $t_dir/utils/win32/
-  cp -af $sysl_dir/{syslinux,extlinux} $t_dir/utils/linux/
-  cp -af $sysl_dir/mbr.bin $t_dir/utils/mbr/
+  # For BIOS machine
+  cp -af $sysl_dir/bios/{menu.c32,vesamenu.c32,chain.c32} $t_dir/syslinux/
+  cp -af $sysl_dir/bios/{syslinux.exe,syslinux64.exe} $t_dir/utils/win32/
+  cp -af $sysl_dir/bios/{syslinux,extlinux} $t_dir/utils/linux/
+  cp -af $sysl_dir/bios/mbr.bin $t_dir/utils/mbr/
   for i in $sysl_extra_c32_chklist; do
-    if [ -e $sysl_dir/$i ]; then
-      cp -af $sysl_dir/$i $t_dir/syslinux/
+    if [ -e $sysl_dir/bios/$i ]; then
+      cp -af $sysl_dir/bios/$i $t_dir/syslinux/
     fi
   done
+  # For EFI machine
+  if [ "$live_efi_boot_loader" = "syslinux" ]; then
+    if [ -d "$sysl_dir/efi" ]; then
+      mkdir -p $t_dir/EFI/boot/
+      cp -af $sysl_dir/efi/bootx64.efi $t_dir/EFI/boot/
+      cp -af $sysl_dir/efi/ldlinux.e64 $t_dir/EFI/boot/
+      cp -af $sysl_dir/efi/*.c32 $t_dir/EFI/boot/
+    fi
+  fi
   [ -d "$sysl_dir" -a -n "$(echo $sysl_dir | grep "sysl_dir")" ] && rm -rf $sysl_dir
 } # end of put_syslinux_makeboot_for_usb_flash
 #
