drbl-functions: functions moved from ocs-functions.
Functions confirm_continue_or_not_default_quit,
confirm_continue_or_not_default_continue, and
confirm_continue_no_default_answer were moved from
ocs-functions.

diff --git a/scripts/sbin/drbl-functions b/scripts/sbin/drbl-functions
--- a/scripts/sbin/drbl-functions
+++ b/scripts/sbin/drbl-functions
@@ -3825,3 +3825,162 @@ remove_opt_in_grub_efi_cfg_block() {
     LC_ALL=C perl -pi -e "$sub_menu_entry_cmd" $GRUB_CONF
   fi
 } # end of remove_opt_in_grub_efi_cfg_block()
+#
+confirm_continue_or_not_default_quit() {
+  local ans_continue
+  local job_before_quit job_des
+  while [ $# -gt 0 ]; do
+    case "$1" in
+      -d|--description)
+         shift
+         if [ -z "$(echo $1 |grep ^-.)" ]; then
+           # skip the -xx option, in case 
+           job_des="$1"
+           shift
+         fi
+         if [ -z "$job_des" ]; then
+           echo "-d is used, but no job_des assigned."
+           echo "$msg_program_stop"
+           [ "$save_restore_error_log" = "yes" ] && copy_error_log
+           exit 1
+         fi
+         ;;
+      -*)     echo "${0}: ${1}: invalid option"
+              echo "$msg_program_stop"
+              [ "$save_restore_error_log" = "yes" ] && copy_error_log
+              exit 2 ;;
+      *)      break ;;
+    esac
+  done
+  job_before_quit="$1"
+  if [ -n "$job_des" ]; then
+    echo "$job_des"
+  fi
+  echo "$msg_are_u_sure_u_want_to_continue"
+  echo -n "[y/N] "
+  read ans_continue
+  case "$ans_continue" in
+       y|Y|[yY][eE][sS])
+          echo "$msg_ok_let_do_it!"
+          ;;
+       *)
+          echo "$msg_program_stop!"
+          [ -n "$job_before_quit" ] && $job_before_quit
+	  my_ocs_exit 1
+          ;;
+  esac
+} # end of confirm_continue_or_not_default_quit
+#
+confirm_continue_or_not_default_continue() {
+  local ans_continue
+  local job_before_quit job_des
+  while [ $# -gt 0 ]; do
+    case "$1" in
+      -d|--description)
+         shift
+         if [ -z "$(echo $1 |grep ^-.)" ]; then
+           # skip the -xx option, in case 
+           job_des="$1"
+           shift
+         fi
+         if [ -z "$job_des" ]; then
+           echo "-d is used, but no job_des assigned."
+           echo "$msg_program_stop"
+           [ "$save_restore_error_log" = "yes" ] && copy_error_log
+           exit 1
+         fi
+         ;;
+      -*)     echo "${0}: ${1}: invalid option"
+              echo "$msg_program_stop"
+              [ "$save_restore_error_log" = "yes" ] && copy_error_log
+              exit 2 ;;
+      *)      break ;;
+    esac
+  done
+  job_before_quit="$1"
+  if [ -n "$job_des" ]; then
+    echo "$job_des"
+  fi
+  echo "$msg_are_u_sure_u_want_to_continue"
+  echo -n "[Y/n] "
+  read ans_continue
+  case "$ans_continue" in
+       n|N|[nN][oO])
+          echo "$msg_program_stop!"
+          [ -n "$job_before_quit" ] && $job_before_quit
+	  my_ocs_exit 1
+          ;;
+       *)
+          echo "$msg_ok_let_do_it!"
+	  ;;
+  esac
+} # end of confirm_continue_or_not_default_continue
+#
+confirm_continue_no_default_answer() {
+  local ans_ ans_continue continue_choice
+  local job_before_quit job_des
+  continue_choice=""
+  while [ $# -gt 0 ]; do
+    case "$1" in
+      -d|--description)
+         shift
+         if [ -z "$(echo $1 |grep ^-.)" ]; then
+           # skip the -xx option, in case 
+           job_des="$1"
+           shift
+         fi
+         if [ -z "$job_des" ]; then
+           echo "-d is used, but no job_des assigned."
+           echo "$msg_program_stop"
+           [ "$save_restore_error_log" = "yes" ] && copy_error_log
+           exit 1
+         fi
+         ;;
+      -*)     echo "${0}: ${1}: invalid option"
+              echo "$msg_program_stop"
+              [ "$save_restore_error_log" = "yes" ] && copy_error_log
+              exit 2 ;;
+      *)      break ;;
+    esac
+  done
+  job_before_quit="$1"
+  while [ -z "$continue_choice" ]; do
+   if [ "$ocs_prompt_mode" = "tui" ]; then
+     # Because dialog/whiptail "--yesno" must have a yes or no, we choose no here.
+     $DIA --backtitle "$msg_nchc_free_software_labs" --title "$msg_nchc_clonezilla" \
+     --defaultno --yesno "${job_des}${msg_are_u_sure_u_want_to_continue}" 0 0 
+     ans_="$?"
+     # Convert ans_ to ans_continue
+     case "$ans_" in
+       0) # yes is chosen
+          ans_continue="yes";;
+       1) # no is chosen
+          ans_continue="no";;
+     esac
+   else
+     if [ -n "$job_des" ]; then
+       echo "$job_des"
+     fi
+     echo -n "$msg_are_u_sure_u_want_to_continue (y/n) "
+     read ans_continue
+   fi
+   case "$ans_continue" in
+        y|Y|[yY][eE][sS])
+           continue_choice="yes"
+           echo "$msg_ok_let_do_it!"
+           ;;
+        n|N|[nN][oO])
+           continue_choice="no"
+           echo "$msg_program_stop!"
+           [ -n "$job_before_quit" ] && $job_before_quit
+	   my_ocs_exit 1
+           ;;
+        *)
+           [ "$BOOTUP" = "color" ] && $SETCOLOR_WARNING
+           echo "$msg_you_have_to_enter_yes_or_no!"
+           [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
+           echo $msg_delimiter_star_line
+           ;;
+   esac
+  done
+} # end of confirm_continue_no_default_answer
