- Program drbl-list-tarball was added to replace list_available_tbz2 and list_latest_tbz2. - Program drbl-prepare-pxelinux and the function get_syslinux_binary_for_dos_linux of drbl-functions was modified to use syslinux xz tarball instead of bz2 tarball because the latest testing one does not provide bz2 format anymore.

diff --git a/scripts/bin/drbl-list-tarball b/scripts/bin/drbl-list-tarball
--- a/scripts/bin/drbl-list-tarball
+++ b/scripts/bin/drbl-list-tarball
@@ -11,14 +11,51 @@ DRBL_SCRIPT_PATH="${DRBL_SCRIPT_PATH:-/usr/share/drbl}"
 
 . $DRBL_SCRIPT_PATH/sbin/drbl-conf-functions
 
+# Settings
+default_comp="xz"
+latest_only="false"
 
 #
-usage () {
-  echo "Usage: `basename $0` [path]"
-  echo "Example:"
-  echo "`basename $0` /mirror/apt/RPMS.drbl-test"
-  echo "`basename $0` http://free.nchc.org.tw/fedora/apt/fedora/linux/2/i386/RPMS.drbl"
+USAGE() {
+  echo "$ocs - To list the available tarball files"
+  echo "Usage:"
+  echo "To run $ocs:"
+  echo "$ocs [OPTION] PATH"
+  echo "Options:"
+  echo "-f, --comp-format FORMAT  Specify the tarball compression format, i.e. gz, bz2, xz. If not assigned, xz will be used."
+  echo "-l, --latest  List the latest version only"
+  echo "Ex:"
+  echo "$ocs /mirror/apt/RPMS.drbl-test"
+  echo "$ocs http://free.nchc.org.tw/syslinux/"
 }
+
+####################
+### Main program ###
+####################
+
+ocs_file="$0"
+ocs=`basename $ocs_file`
+#
+while [ $# -gt 0 ]; do
+ case "$1" in
+   -f|--comp-format) 
+           shift; 
+           if [ -z "$(echo $1 |grep ^-.)" ]; then
+             # skip the -xx option, in case 
+             suf="$1"
+             shift;
+           fi
+           [ -z "$ocsroot" ] && USAGE && exit 1
+           ;;
+   -l|--latest) latest_only="true"; shift;;
+   -*)     echo "${0}: ${1}: invalid option" >&2
+           USAGE >& 2
+           exit 2 ;;
+   *)      break ;;
+ esac
+done
+
+SRC="$1"
 
 # Try to help people figure out if/when this file has DOS line terminators
 # Chances are the initial #!/bin/sh will fail with a cryptic "not found" msg
@@ -30,16 +67,27 @@ case "$NL" in '');; *)                                                    #
     exit 1 ;;                                                             #
 esac                                                                      #
 
-SRC=$1
-[ -z "$SRC" ] && echo "You must provide the URL or PATH!" && usage && exit 1
+if [ -z "$suf" ]; then
+  suf="$default_comp"
+fi
+if [ -z "$SRC" ]; then
+  echo "You must assign the URL or PATH!" 
+  USAGE 
+  exit 1
+fi
 
 case "$SRC" in */);; *) SRC=$SRC/;; esac	# URL must end in slash
 
-#-------------------------------------------------------------------------------
 #
-# Find all redhat patches available
-#
+if [ "$latest_only" = "true" ]; then
+  sort_opt="sort -r -V"
+  filter_opt="head -n 1"
+else
+  sort_opt="sort"
+  filter_opt="cat"
+fi
 
+#
 if [ -d $SRC ] ;then	# local directory
     (cd $SRC && ls -l)
 else			# ftp directory
@@ -47,7 +95,7 @@ else			# ftp directory
 	ftp://*)
             ( echo set ftp:passive-mode on
 	      # Steven Shiau modified to use lftp.
-	      echo rels ) | lftp $SRC 2>/dev/null | grep -E '\.tar.bz2\>'
+	      echo rels ) | lftp $SRC 2>/dev/null | grep -Ew "\.tar\.${suf}"
             ;;
 	http://*)
 	    # Steven Shiau modified to use lftp instead of lynx
@@ -62,4 +110,4 @@ else			# ftp directory
     # In case dir -L fails, we need to add ^[-l] to strip the junk msg.
     # Some repo output DOS (CR/LF), 
     # convert to Unix format: sed 's/[^[:print:]]$//'
-fi | sed 's/[^[:print:]]$//' | sed -r -n '/tar.bz2$/s/^[-l].* //p' | while read x; do basename $x; done | sort
+fi | sed 's/[^[:print:]]$//' | sed -r -n "/tar.${suf}$/s/^[-l].* //p" | while read x; do basename $x; done | $sort_opt | $filter_opt
