- The grep function "NEWER" was renamed as "GREP_NEWER" and defined only in drbl-functions, used for all related scripts. - Program drbl-list-tarball was renamed as list_available_tarball. - Program list_latest_tarball was added and used in function get_syslinux_binary_for_dos_linux of drbl-functions.

diff --git a/scripts/bin/list_latest_tarball b/scripts/bin/list_latest_tarball
--- a/scripts/bin/list_latest_tarball
+++ b/scripts/bin/list_latest_tarball
@@ -4,31 +4,35 @@
 # http://staff.washington.edu/corey/tools.html
 # Author: Corey Satten, corey @ cac.washington.edu, 06/26/03, release 1.8
 #============================================================================
-# Modified by Steven Shiau <steven _at_ nchc org tw> 12/12/04
-# We use this one to find the last version rpms in our apt repository.
-# Because we might have a lot of drbl-setup rpms...
-# drbl-script-1.0-45drbl.i386.rpm
-# drbl-script-1.1-19drbl.i386.rpm
-# drbl-script-1.1-1drbl.i386.rpm    
-# drbl-setup-1.2-7drbl.i386.rpm
-# we just want to list the last one drbl-setup-1.2-7drbl.i386.rpm
+# Modified by Steven Shiau <steven _at_ nchc org tw> Sep/03/07
+# We use this one to find the last version tar.bz2 in the repository.
+# Because we might have a lot of tar.bz2...
+# clonezilla-2.1.8-1.tar.bz2
+# clonezilla-2.1.8-2.tar.bz2
+# clonezilla-2.1.8-3.tar.bz2
+# clonezilla-2.1.9-1.tar.bz2
+# clonezilla-2.1.9-2.tar.bz2
+# clonezilla-2.2.0-1.tar.bz2
+# clonezilla-2.2.0-2.tar.bz2
+# clonezilla-2.2.0-3.tar.bz2
+# clonezilla-2.2.0-4.tar.bz2
+# we just want to list the last one clonezilla-2.2.0-4.tar.bz2
 #============================================================================
-# 2006/6/24 Steven Shiau modified it to use lftp for http instead of lynx, since
-# 1. For some apache2, "lynx -dump" will get the html format instead of plain text
-# 2. lynx does not support http_proxy and ftp_proxy.
-# Now this program is based on list_available_rpm.
+# "$GREP_NEWER" is in drbl-functions
 
 # Load DRBL setting and functions
 DRBL_SCRIPT_PATH="${DRBL_SCRIPT_PATH:-/usr/share/drbl}"
 
 . $DRBL_SCRIPT_PATH/sbin/drbl-conf-functions
 
+# Default settings
+suf_default="gz"
 #
-usage () {
+USAGE () {
   echo "Usage: `basename $0` [path]"
   echo "Example:"
-  echo "`basename $0` /mirror/apt/RPMS.drbl-test"
-  echo "`basename $0` http://opensource.nchc.org.tw/fedora/apt/fedora/linux/2/i386/RPMS.drbl"
+  echo "`basename $0` /mirror/src/stable/"
+  echo "`basename $0` http://free.nchc.org.tw/drbl-core/src/stable/"
 }
 
 # Try to help people figure out if/when this file has DOS line terminators
@@ -41,13 +45,35 @@ case "$NL" in '');; *)                                                    #
     exit 1 ;;                                                             #
 esac                                                                      #
 
+#
+while [ $# -gt 0 ]; do
+ case "$1" in
+   -f|--comp-format) 
+           shift; 
+           if [ -z "$(echo $1 |grep ^-.)" ]; then
+             # skip the -xx option, in case 
+             suf="$1"
+             shift;
+           fi
+           [ -z "$ocsroot" ] && USAGE && exit 1
+           ;;
+   -*)     echo "${0}: ${1}: invalid option" >&2
+           USAGE >& 2
+           exit 2 ;;
+   *)      break ;;
+ esac
+done
+
 SRC=$1
-[ -z "$SRC" ] && echo "You must provide the URL or PATH!" && usage && exit 1
+[ -z "$SRC" ] && echo "You must provide the URL or PATH!" && USAGE && exit 1
 
 case "$SRC" in */);; *) SRC=$SRC/;; esac	# URL must end in slash
 
+#
+[ -z "$suf" ] && suf="$suf_default"
+
 #-------------------------------------------------------------------------------
-list_available_rpm $SRC |
+list_available_tarball -f $suf $SRC |
 #-------------------------------------------------------------------------------
 #
 # Find all installed packages with patches
@@ -59,8 +85,8 @@ list_available_rpm $SRC |
         gawk "$GREP_NEWER"'	# omit all but newest of multiple available patches
   		{ L0=R0; L1=R1; L2=R2
 		  R0=$0
-		  R1=$0; sub(/\.[^.]+\.rpm$/,"",R1) 	# pkg name+version
-		  R2=$0; sub(/-[^-]+-[^-]+$/, "",R2) 	# pkg name-version
+		  R1=$0; sub(/\.[^.]+.${suf}$/,"",R1) 	# pkg name+version
+		  R2=$0; sub(/-[^-]+$/, "",R2) 	# pkg name-version
 		  if ((R2 == L2) && newer(R1, L1)) {R0=L0; R1=L1}
 		  if ((R2 != L2) && L0) {print L0}
 		}
