Add nmap mechanism to detect DHCP service.
Add nmap mechanism as the primary method to detect DHCP service.

diff --git a/sbin/drbl-find-dhcp-srv b/sbin/drbl-find-dhcp-srv
--- a/sbin/drbl-find-dhcp-srv
+++ b/sbin/drbl-find-dhcp-srv
@@ -31,6 +31,123 @@ USAGE() {
     echo "   $ocs -i eth1 dhcp.txt"
     echo
 } # end of USAGE
+#
+get_dhcpsrv_info_from_nagios() {
+  local eth_ d_result
+  local dhcp_srv_ip dhcp_client_ip rc_=1
+  eth_="$1"
+  d_result="$2"
+  if [ -z "$eth_" ]; then
+    echo "Variable eth_ was not assigned in function get_dhcpsrv_info_from_nagios."
+    exit 1
+  fi
+  if [ -z "$d_result" ]; then
+    echo "Variable d_result was not assigned in function get_dhcpsrv_info_from_nagios."
+    exit 1
+  fi
+  # TODO: check_dhcp might quit very quickly. How to run it until we find the results, but not keep it too long?
+  /usr/lib/nagios/plugins/check_dhcp -v -i $eth_ > $d_result &
+  time_left="$timeout"
+  while [ "$time_left" -ne 0 ]; do
+    echo -n "$time_left "
+    # Result is like:
+    # recv_result: 300
+    # receive_dhcp_packet() result: 300
+    # receive_dhcp_packet() source: 192.168.22.254
+    # Result=OK
+    # DHCPOFFER from IP address 192.168.22.254 via 192.168.22.254
+    # DHCPOFFER XID: 699683243 (0x29B451AB)
+    # DHCPOFFER chaddr: 000C2992D4D0
+    # DHCPOFFER ciaddr: 0.0.0.0
+    # DHCPOFFER yiaddr: 192.168.22.1
+    # DHCPOFFER siaddr: 192.168.22.254
+    # DHCPOFFER giaddr: 0.0.0.0
+    dhcp_srv_ip="$(LC_ALL=C grep -E "^DHCPOFFER siaddr:" $d_result 2>/dev/null | awk -F":" '{print $2}')"
+    dhcp_client_ip="$(LC_ALL=C grep -E "^DHCPOFFER yiaddr:" $d_result 2>/dev/null | awk -F":" '{print $2}')"
+    if [ -n "$dhcp_srv_ip" -a -n "$dhcp_client_ip" ]; then
+      dhcp_srv_ip="$(echo $dhcp_srv_ip)"  # Strip leading spaces.
+      dhcp_client_ip="$(echo $dhcp_client_ip)"  # Strip leading spaces.
+      echo
+      echo "Found DHCP service. Ethernet card, DHCP server, Available DHCP client: $eth_, $dhcp_srv_ip, $dhcp_client_ip"
+      if [ -n "$out_f" ]; then
+        cat <<-DHCP_END > $out_f
+DHCPOFFER_eth="$eth_"
+DHCPOFFER_siaddr="$dhcp_srv_ip"
+DHCPOFFER_yiaddr="$dhcp_client_ip"
+DHCPOFFER_netmask=""
+DHCPOFFER_prefix=""
+DHCP_END
+      fi
+      rc_=0
+      break
+    fi
+    sleep 1
+    time_left="$((time_left - 1))" 
+  done
+  return $rc_
+} # end of get_dhcpsrv_info_from_nagios
+#
+get_dhcpsrv_info_from_nmap() {
+  local eth_ d_result
+  local dhcp_srv_ip dhcp_client_ip dhcp_client_nm dhcp_client_prefix rc_=1
+  eth_="$1"
+  d_result="$2"
+  if [ -z "$eth_" ]; then
+    echo "Variable eth_ was not assigned in function get_dhcpsrv_info_from_nmap."
+    exit 1
+  fi
+  if [ -z "$d_result" ]; then
+    echo "Variable d_result was not assigned in function get_dhcpsrv_info_from_nmap."
+    exit 1
+  fi
+  LC_ALL=C nmap --script broadcast-dhcp-discover -e $eth_ > $d_result 2>&1 &
+  time_left="$timeout"
+  while [ "$time_left" -ne 0 ]; do
+    echo -n "$time_left "
+    # Nmap result is like:
+    # nmap --script broadcast-dhcp-discover -e macvlan0
+    #
+    # Starting Nmap 7.12 ( https://nmap.org ) at 2017-01-29 18:09 CST
+    # Pre-scan script results:
+    # | broadcast-dhcp-discover:
+    # |   Response 1 of 1:
+    # |     IP Offered: 192.168.120.5
+    # |     DHCP Message Type: DHCPOFFER
+    # |     Server Identifier: 192.168.120.254
+    # |     IP Address Lease Time: 5m00s
+    # |     Subnet Mask: 255.255.255.0
+    # |     Router: 192.168.120.254
+    # |     Domain Name Server: 8.8.8.8, 8.8.4.4
+    # |     Domain Name: nchc.org.tw
+    dhcp_srv_ip="$(LC_ALL=C grep -E "^\|[[:space:]]*Server Identifier:" $d_result 2>/dev/null | awk -F":" '{print $2}')"
+    dhcp_client_ip="$(LC_ALL=C grep -E "^\|[[:space:]]*IP Offered:" $d_result 2>/dev/null | awk -F":" '{print $2}')"
+    dhcp_client_nm="$(LC_ALL=C grep -E "^\|[[:space:]]*Subnet Mask:" $d_result 2>/dev/null | awk -F":" '{print $2}')"
+    # convert netmask to prefix length
+    if [ -n "$dhcp_client_nm" ]; then
+      dhcp_client_prefix="$(LC_ALL=C ipcalc 0.0.0.0 $dhcp_client_nm | awk -F" " '/^Netmask:/ {print $4}')"
+    fi
+    if [ -n "$dhcp_srv_ip" -a -n "$dhcp_client_ip" ]; then
+      dhcp_srv_ip="$(echo $dhcp_srv_ip)"  # Strip leading spaces.
+      dhcp_client_ip="$(echo $dhcp_client_ip)"  # Strip leading spaces.
+      echo
+      echo "Found DHCP service. Ethernet card, DHCP server, Available DHCP client: $eth_, $dhcp_srv_ip, $dhcp_client_ip"
+      if [ -n "$out_f" ]; then
+        cat <<-DHCP_END > $out_f
+DHCPOFFER_eth="$eth_"
+DHCPOFFER_siaddr="$dhcp_srv_ip"
+DHCPOFFER_yiaddr="$dhcp_client_ip"
+DHCPOFFER_netmask="$dhcp_client_nm"
+DHCPOFFER_prefix="$dhcp_client_prefix"
+DHCP_END
+      fi
+      rc_=0
+      break
+    fi
+    sleep 1
+    time_left="$((time_left - 1))" 
+  done
+  return $rc_
+} # end of get_dhcpsrv_info_from_nmap
 
 ####################
 ### Main program ###
@@ -73,11 +190,11 @@ out_f="$1"
 ask_and_load_lang_set
 
 #
-if [ ! -e /usr/lib/nagios/plugins/check_dhcp ]; then
+if [ ! -e /usr/lib/nagios/plugins/check_dhcp ] && ! `type nmap >/dev/null 2>&1` ; then
   [ "$BOOTUP" = "color" ] && $SETCOLOR_FAILURE
-  echo "File /usr/lib/nagios/plugins/check_dhcp not found!"
+  echo "File /usr/lib/nagios/plugins/check_dhcp or program nmap not found!"
   [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
-  echo "Please install Nagios plugins. On Debian/Ubuntu system, the required package is monitoring-plugins-basic."
+  echo "Please install Nagios plugins or nmap program. On Debian/Ubuntu system, the required package is monitoring-plugins-basic or nmap."
   echo "$msg_program_stop!"
   my_ocs_exit 1
 fi
@@ -97,6 +214,7 @@ else
     fi
   done
 fi
+
 dhcp_req_result="$(mktemp /tmp/DHCP_REQ.XXXXXX)"
 rc=1
 for ieth in $eth_port; do
@@ -104,43 +222,13 @@ for ieth in $eth_port; do
   # Clean content first.
   > $dhcp_req_result
   echo -n "Detecting DHCP services... "
-  # TODO: check_dhcp might quit very quickly. How to run it until we find the results, but not keep it too long?
-  /usr/lib/nagios/plugins/check_dhcp -v -i $ieth > $dhcp_req_result &
-  time_left="$timeout"
-  while [ "$time_left" -ne 0 ]; do
-    echo -n "$time_left "
-    # Result is like:
-    # recv_result: 300
-    # receive_dhcp_packet() result: 300
-    # receive_dhcp_packet() source: 192.168.22.254
-    # Result=OK
-    # DHCPOFFER from IP address 192.168.22.254 via 192.168.22.254
-    # DHCPOFFER XID: 699683243 (0x29B451AB)
-    # DHCPOFFER chaddr: 000C2992D4D0
-    # DHCPOFFER ciaddr: 0.0.0.0
-    # DHCPOFFER yiaddr: 192.168.22.1
-    # DHCPOFFER siaddr: 192.168.22.254
-    # DHCPOFFER giaddr: 0.0.0.0
-    dhcp_srv_ip="$(LC_ALL=C grep -E "^DHCPOFFER siaddr:" $dhcp_req_result 2>/dev/null | awk -F":" '{print $2}')"
-    dhcp_client_ip="$(LC_ALL=C grep -E "^DHCPOFFER yiaddr:" $dhcp_req_result 2>/dev/null | awk -F":" '{print $2}')"
-    if [ -n "$dhcp_srv_ip" -a -n "$dhcp_client_ip" ]; then
-      dhcp_srv_ip="$(echo $dhcp_srv_ip)"  # Strip leading spaces.
-      dhcp_client_ip="$(echo $dhcp_client_ip)"  # Strip leading spaces.
-      echo
-      echo "Found DHCP service. Ethernet card, DHCP server, Available DHCP client: $ieth, $dhcp_srv_ip, $dhcp_client_ip"
-      if [ -n "$out_f" ]; then
-        cat <<-DHCP_END > $out_f
-DHCPOFFER_eth="$ieth"
-DHCPOFFER_siaddr="$dhcp_srv_ip"
-DHCPOFFER_yiaddr="$dhcp_client_ip"
-DHCP_END
-      fi
-      rc=0
-      break
-    fi
-    sleep 1
-    time_left="$((time_left - 1))" 
-  done
+  get_dhcpsrv_info_from_nmap $ieth $dhcp_req_result
+  rc=$?
+  if [ "$rc" -ne 0 ]; then
+    echo ""
+    echo "Trying another method, i.e., Nagios method..."
+    get_dhcpsrv_info_from_nagios $ieth $dhcp_req_result
+  fi
 done
 
 # Clean temp file
