- Bug fixed: for CentOS 7, there is no need to copy the modified halt and rc.sysinit files for DRBL client.

diff --git a/sbin/drblpush b/sbin/drblpush
--- a/sbin/drblpush
+++ b/sbin/drblpush
@@ -3209,16 +3209,18 @@ case "$OS_type" in
     if [ -f "${drbl_setup_path}/files/${OS_type}/${OS_Version}/rc.sysinit.${OS_Version}.drbl" ]; then
       cp -f ${drbl_setup_path}/files/${OS_type}/${OS_Version}/rc.sysinit.${OS_Version}.drbl $drbl_common_root/etc/rc.d/rc.sysinit
     else
-      # Can not find fine-tune file, show warning. This is only necessary for CentOS, since for Fedora, when >= version 17, no required. //NOTE// From drbl 2.x, only CentOS and Fedora are supported.
+      # Can not find fine-tune file, show warning. This is only necessary for CentOS <= 6, since for Fedora, when >= version 17, no required. //NOTE// From drbl 2.x, only CentOS and Fedora are supported.
       OS_Version_Major="${OS_Version:0:3}"  # E.g. CO5.8 -> CO5
       case "$OS_Version" in
         CO*)
-        most_related_ver="$(LC_ALL=C find $drbl_setup_path/files/$OS_type/${OS_Version_Major}* -type d -exec basename {} \; 2>/dev/null | sort | uniq | tail -n 1)"
-        [ "$BOOTUP" = "color" ] && $SETCOLOR_WARNING
-        echo "Warning! The fine-tune file ${drbl_setup_path}/files/${OS_type}/${OS_Version}/rc.sysinit.${OS_Version}.drbl was not found. Using ${drbl_setup_path}/files/${OS_type}/${most_related_ver}/rc.sysinit.${most_related_ver}.drbl as /etc/rc.d/rc.sysinit for DRBL clients!"
-        echo "This may cause some problems to DRBL clients!"
-        [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
-        [ -n "$most_related_ver" ] && cp -f ${drbl_setup_path}/files/${OS_type}/${most_related_ver}/rc.sysinit.${most_related_ver}.drbl $drbl_common_root/etc/rc.d/rc.sysinit
+        if ! is_systemd_init; then
+          most_related_ver="$(LC_ALL=C find $drbl_setup_path/files/$OS_type/${OS_Version_Major}* -type d -exec basename {} \; 2>/dev/null | sort | uniq | tail -n 1)"
+          [ "$BOOTUP" = "color" ] && $SETCOLOR_WARNING
+          echo "Warning! The fine-tune file ${drbl_setup_path}/files/${OS_type}/${OS_Version}/rc.sysinit.${OS_Version}.drbl was not found. Using ${drbl_setup_path}/files/${OS_type}/${most_related_ver}/rc.sysinit.${most_related_ver}.drbl as /etc/rc.d/rc.sysinit for DRBL clients!"
+          echo "This may cause some problems to DRBL clients!"
+          [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
+          [ -n "$most_related_ver" ] && cp -f ${drbl_setup_path}/files/${OS_type}/${most_related_ver}/rc.sysinit.${most_related_ver}.drbl $drbl_common_root/etc/rc.d/rc.sysinit
+	fi
 	;;
       esac
     fi
@@ -3559,16 +3561,18 @@ else
   if [ -f "$drbl_setup_path/files/${OS_type}/${OS_Version}/halt.$OS_Version.drbl" ]; then
     cp -f $drbl_setup_path/files/${OS_type}/${OS_Version}/halt.$OS_Version.drbl $drbl_common_root/etc/init.d/halt
   else
-    # not Debian, it's RH-like (BSD style), so show warning. This is only necessary for CentOS, since for Fedora, when >= version 17, no required. //NOTE// From drbl 2.x, only CentOS and Fedora are supported.
+    # not Debian, it's RH-like (BSD style), so show warning. This is only necessary for CentOS <= 6, since for Fedora, when >= version 17, no required. //NOTE// From drbl 2.x, only CentOS and Fedora are supported.
     OS_Version_Major="${OS_Version:0:3}"  # E.g. CO5.8 -> CO5
     case "$OS_Version" in
     CO*)
-      most_related_ver="$(LC_ALL=C find $drbl_setup_path/files/$OS_type/${OS_Version_Major}* -type d -exec basename {} \; 2>/dev/null | sort | uniq | tail -n 1)"
-      [ "$BOOTUP" = "color" ] && $SETCOLOR_WARNING
-      echo "Warning! The fine-tune file ${drbl_setup_path}/files/${OS_type}/${OS_Version}/halt.${OS_Version}.drbl was not found. Using $drbl_setup_path/files/${OS_type}/${most_related_ver}/halt.${most_related_ver}.drbl as /etc/init.d/halt for DRBL clients!"
-      echo "This may cause some problems to DRBL clients!"
-      [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
-      [ -n "$most_related_ver" ] && cp -f $drbl_setup_path/files/${OS_type}/${most_related_ver}/halt.${most_related_ver}.drbl $drbl_common_root/etc/init.d/halt
+      if ! is_systemd_init; then
+        most_related_ver="$(LC_ALL=C find $drbl_setup_path/files/$OS_type/${OS_Version_Major}* -type d -exec basename {} \; 2>/dev/null | sort | uniq | tail -n 1)"
+        [ "$BOOTUP" = "color" ] && $SETCOLOR_WARNING
+        echo "Warning! The fine-tune file ${drbl_setup_path}/files/${OS_type}/${OS_Version}/halt.${OS_Version}.drbl was not found. Using $drbl_setup_path/files/${OS_type}/${most_related_ver}/halt.${most_related_ver}.drbl as /etc/init.d/halt for DRBL clients!"
+        echo "This may cause some problems to DRBL clients!"
+        [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
+        [ -n "$most_related_ver" ] && cp -f $drbl_setup_path/files/${OS_type}/${most_related_ver}/halt.${most_related_ver}.drbl $drbl_common_root/etc/init.d/halt
+      fi
       ;;
     esac
   fi
